### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by EliteP** [SMBB/R6-Internal-cheat#2]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'C:\Program Files (x86)\Microsoft Research\Detours Express 3.0\lib.X64\detours.lib'	Project Frost	C:\Users\(MyUser)\OneDrive\Desktop\R6-Internal-Cheat\LINK

**Comment by oaaron99** [comment]
You need to link detours.lib in your project settings

https://github.com/SMBB/R6-Internal-cheat/blob/master/Detours/lib.X64/detours.lib

**Comment by EliteP** [comment]
Thank you
